# Generated by Django 5.0 on 2023-12-15 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('foundation_date', models.DateField()),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField(max_length=50)),
                ('admission_year', models.IntegerField(default=None)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universities.university')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': ('Students',),
            },
        ),
    ]
